### ISSUE TITLE
ValueError: incomplete format

### ISSUE THREAD

**Issue by rsk222** [hdetering/discomark#2]
Hello,
I am trying to run discomark on a Mac running OSX 10.12.3. Things went along fine until step five, when I encountered the following error:

[5] Designing primers based on multiple alignments...
Traceback (most recent call last):
  File "run_project.py", line 139, in <module>
    steps.design_primers(source_dir, primer_dir, settings, logfile)
  File "/Users/redacted/discomark/discomark/steps.py", line 201, in design_primers
    primerpairs = prifipy.findprimers(0, list(aln), summary, l, settings, logfile)
  File "/Users/redacted/discomark/util/prifipy/primerfinder_ver2.py", line 2110, in findprimers
    s,pro,contra=scoreprimerpair( p1,p2,realindices,intronsbetweenprimers, 1)
  File "/Users/redacted/discomark/util/prifipy/primerfinder_ver2.py", line 509, in scoreprimerpair
    contra.append("%5.1f: Fw GC content >= 75%"%p1.gcscore )
ValueError: incomplete format

I am only somewhat familiar with python and I am not really sure what is wrong. 
Thank you for your help.

**Comment by hdetering** [comment]
Hi rsk222,

thank you for using DiscoMark and for reporting this error!

The problem was due to some deprecated format strings in the Python code of a submodule. The issue should be fixed now (in `master` branch). Please confirm by updating your code (`git pull`) and re-running your analysis.

Any kind of feedback is highly appreciated.

Have a nice day
-- Harry

**Comment by hdetering** [comment]
Dear rsk222,

did you give it another try? Is this problem resolved now?

Thanks and have a good one
-- Harry

**Comment by rsk222** [comment]
Hi Harry,
Sorry for the delayed response. I ended up making some manual adjustments to the code a few months ago when I was initially running discomark (escaping a % and changing a variable where it seemed to be misspelled). I got it to run at the time, for the most part. I was never able to get the BLAST part to run, so I ended up using the --no-primer-blast option and it would produce results. 

I have just downloaded the updated code and rerun my analyses. It got to step three and is giving me a new error message:

[3] Trimming alignments...
Traceback (most recent call last):
  File "run_project.py", line 118, in <module>
    steps.trim_alignments(aligned_dir, trimmed_dir, settings, logfile)
  File "/Users/rachelskinner1/discomark/discomark/steps.py", line 80, in trim_alignments
    subprocess.call(trimal_params, stdout=log_fh, stderr=log_fh)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Thanks,
rsk222

**Comment by hdetering** [comment]
Hi rsk222,

thanks a lot for giving it another go.

This error is at an earlier step in the pipeline than the last one. It is most likely due to the fact that the `trimal` executable cannot be located. If you don't have trimal installed, you can run the command
```
export PATH=$PATH:$PWD/discomark/bin/mac
```
before running DiscoMark. (You can verify if the executable is available by just typing `trimal` in the terminal, which should print the trimal usage info.)

Otherwise I'm glad that you got results earlier after fixing the error yourself. We are also very interested to hear how useful you found the output and appreciate feedback a lot.

Best,
Harry
